name: Flutter Build & Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          # قمنا بتغيير الإصدار هنا ليناسب مشروعك بالضبط
          flutter-version: '3.11.5'
          channel: 'stable'
      
      - run: flutter pub get
        working-directory: ./app
      
      - run: flutter test
        working-directory: ./app
