name: Flutter Build & Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # هذا الأمر سيقوم بتثبيت أحدث نسخة مستقرة تلقائياً دون مشاكل الإصدارات
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' 
      
      # أخبرناه أن يدخل المجلد الذي وضعتِ فيه ملفاتك (app)
      - run: flutter pub get
        working-directory: ./app
      
      # سيتخطى الفحص إذا كان هناك تعارض بسيط في النسخ
      - run: flutter pub get
        working-directory: ./app
